{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ba62e9a1",
   "metadata": {
    "vscode": {
     "languageId": "plaintext"
    }
   },
   "outputs": [],
   "source": [
    "\n",
    "from langgraph.graph import StateGraph, START, END\n",
    "from typing import TypedDict, Literal\n",
    "\n",
    "from pydantic import BaseModel, Field\n",
    "from langchain_groq import ChatGroq\n",
    "from dotenv import load_dotenv\n",
    "\n",
    "load_dotenv()\n",
    "\n",
    "model = ChatGroq(\n",
    "    model=\"openai/gpt-oss-20b\",\n",
    ")\n",
    "\n",
    "class DevSupportState(TypedDict):\n",
    "    developer_query: str\n",
    "    query_category: str\n",
    "    response: str\n",
    "    tools_used: list[str]\n",
    "\n",
    "\n",
    "class DevQueryClassification(BaseModel):\n",
    "    category: Literal[\"bug\", \"architecture\", \"performance\", \"devops\", \"general\"]\n",
    "    confidence: float = Field(description=\"0부터 1까지 사이 숫자로 표현한 신뢰도 점수 (소수점 4자리까지)\")\n",
    "    reasoning: str = Field(description=\"해당 카테고리를 선택한 기술적 판단 근거\")\n",
    "\n",
    "\n",
    "def classify_dev_query(state: DevSupportState):\n",
    "    print(\"개발자의 질문을 분석합니다.\")\n",
    "\n",
    "    classifier_model = model.with_structured_output(DevQueryClassification)\n",
    "\n",
    "    prompt = f\"\"\"\n",
    "    당신은 시니어 풀스택 개발자이자 기술 지원 전문가입니다.\n",
    "    아래 개발자의 질문을 다음 카테고리 중 하나로 분류해 주세요\n",
    "\n",
    "    - bug : 코드 오류, 예외 처리, 디버깅, 예상치 못한 동작 등 버그 관련 문제\n",
    "    - architecture : 설계 패턴, 모듈 구조, 시스템 설계, 코드 리팩토링, 기술 스택 선정 등\n",
    "    - performance : 속도 저하, 메모리 누수, 쿼리 최적화, 캐싱, 병목 현상 분석 등\n",
    "    - devops : 배포, CI/CD, 도커, 쿠버네티스, 클라우드 인프라, 환경 설정 등\n",
    "    - general : 라이브러리 사용법, 언어 문법, 개발 도구, 학습 방향 등 일반 개발 문의\n",
    "\n",
    "    개발자 질문:\n",
    "\n",
    "    {state['developer_query']}\n",
    "\n",
    "    질문의 핵심 의도를 기준으로 가장 적합한 카테고리로 정확하게 분류하세요.\n",
    "    \"\"\"\n",
    "\n",
    "    classification: DevQueryClassification = classifier_model.invoke(prompt)\n",
    "\n",
    "    print(f\"분류된 카테고리 : {classification.category}\")\n",
    "    print(f\"신뢰도 : {classification.confidence:.2f}\")\n",
    "    print(f\"판단 근거 : {classification.reasoning}\")\n",
    "\n",
    "    return {\n",
    "        \"query_category\": classification.category,\n",
    "    }\n",
    "\n",
    "\n",
    "def handle_bug(state: DevSupportState):\n",
    "    print(\"버그 관련 문제를 인식하고 처리를 시작합니다!\")\n",
    "\n",
    "    prompt = f\"\"\"\n",
    "    당신은 디버깅 전문 시니어 개발자입니다.\n",
    "    아래 개발자의 버그 관련 문제를 분석하고 해결 방법을 제시해 주세요\n",
    "\n",
    "    {state['developer_query']}\n",
    "\n",
    "    반드시 다음 내용을 포함하여 답변하세요:\n",
    "\n",
    "    - 오류 메시지 또는 증상을 바탕으로 가능한 원인을 분석합니다.\n",
    "    - 단계별 디버깅 방법을 구체적으로 안내합니다.\n",
    "    - 수정된 코드 예시 또는 해결 방향을 제시합니다.\n",
    "    - 동일한 버그가 재발하지 않도록 예방 방법을 안내합니다.\n",
    "\n",
    "    코드 예시가 필요한 경우 명확하고 간결하게 작성하세요.\n",
    "    \"\"\"\n",
    "\n",
    "    response = model.invoke(prompt).content\n",
    "\n",
    "    print(\"버그 처리 노드 답변 생성 완료!\")\n",
    "\n",
    "    return {\n",
    "        \"response\": response,\n",
    "        \"tools_used\": [\"stack_trace_analyzer\", \"code_debugger\", \"error_log_parser\"],\n",
    "    }\n",
    "\n",
    "\n",
    "def handle_architecture(state: DevSupportState):\n",
    "    print(\"설계 관련 문제를 인식하고 처리를 시작합니다!\")\n",
    "\n",
    "    prompt = f\"\"\"\n",
    "    당신은 소프트웨어 아키텍처 전문가입니다.\n",
    "    아래 개발자의 설계 관련 질문에 대해 명확한 방향을 제시해 주세요:\n",
    "\n",
    "    {state['developer_query']}\n",
    "\n",
    "    반드시 다음 내용을 포함하여 답변하세요:\n",
    "\n",
    "    - 현재 상황에 적합한 설계 패턴 또는 아키텍처 방식을 추천합니다.\n",
    "    - 추천하는 방식의 장단점을 균형 있게 설명합니다.\n",
    "    - 실제 적용 시 고려해야 할 트레이드오프를 안내합니다.\n",
    "    - 참고할 만한 Best Practice 또는 실제 사례를 언급합니다.\n",
    "\n",
    "    추상적인 조언보다는 현실적으로 적용 가능한 구체적인 방향을 제시하세요.\n",
    "    \"\"\"\n",
    "\n",
    "    response = model.invoke(prompt).content\n",
    "\n",
    "    print(\"아키텍처 처리 노드 답변 생성 완료!\")\n",
    "\n",
    "    return {\n",
    "        \"response\": response,\n",
    "        \"tools_used\": [\"architecture_pattern_db\", \"tech_stack_advisor\", \"design_doc_generator\"],\n",
    "    }\n",
    "\n",
    "\n",
    "def handle_performance(state: DevSupportState):\n",
    "    print(\"성능 관련 문제를 인식하고 처리를 시작합니다!\")\n",
    "\n",
    "    prompt = f\"\"\"\n",
    "    당신은 성능 최적화 전문 시니어 개발자입니다.\n",
    "    아래 개발자의 성능 관련 문제를 분석하고 개선 방법을 제시해 주세요:\n",
    "\n",
    "    {state['developer_query']}\n",
    "\n",
    "    반드시 다음 내용을 포함하여 답변하세요:\n",
    "\n",
    "    - 성능 저하의 가능한 원인(병목 지점)을 분석합니다.\n",
    "    - 프로파일링 및 성능 측정 방법을 구체적으로 안내합니다.\n",
    "    - 우선순위가 높은 최적화 방법을 단계별로 제시합니다.\n",
    "    - 캐싱, 인덱싱, 비동기 처리 등 적용 가능한 기법을 설명합니다.\n",
    "\n",
    "    수치나 예시를 활용하여 개선 효과를 구체적으로 설명하세요.\n",
    "    \"\"\"\n",
    "\n",
    "    response = model.invoke(prompt).content\n",
    "\n",
    "    print(\"성능 처리 노드 답변 생성 완료!\")\n",
    "\n",
    "    return {\n",
    "        \"response\": response,\n",
    "        \"tools_used\": [\"profiler\", \"query_analyzer\", \"benchmark_tool\", \"memory_inspector\"],\n",
    "    }\n",
    "\n",
    "\n",
    "def handle_devops(state: DevSupportState):\n",
    "    print(\"배포/인프라 관련 문제를 인식하고 처리를 시작합니다!\")\n",
    "\n",
    "    prompt = f\"\"\"\n",
    "    당신은 DevOps 및 클라우드 인프라 전문가입니다.\n",
    "    아래 개발자의 배포 및 인프라 관련 문제를 분석하고 해결 방법을 제시해 주세요:\n",
    "\n",
    "    {state['developer_query']}\n",
    "\n",
    "    반드시 다음 내용을 포함하여 답변하세요:\n",
    "\n",
    "    - 문제의 원인을 인프라, 환경 설정 관점에서 분석합니다.\n",
    "    - 구체적인 설정 파일 예시 또는 명령어를 포함하여 해결 방법을 안내합니다.\n",
    "    - CI/CD 파이프라인 개선이 필요한 경우 단계별 구성 방법을 설명합니다.\n",
    "    - 보안, 확장성, 안정성 측면에서 고려해야 할 사항을 안내합니다.\n",
    "\n",
    "    실제 운영 환경에서 바로 적용할 수 있는 실용적인 내용으로 작성하세요.\n",
    "    \"\"\"\n",
    "\n",
    "    response = model.invoke(prompt).content\n",
    "\n",
    "    print(\"DevOps 처리 노드 답변 생성 완료!\")\n",
    "\n",
    "    return {\n",
    "        \"response\": response,\n",
    "        \"tools_used\": [\"pipeline_manager\", \"container_registry\", \"cloud_config_validator\", \"log_aggregator\"],\n",
    "    }\n",
    "\n",
    "\n",
    "def handle_general_dev(state: DevSupportState):\n",
    "    print(\"일반 개발 문의를 인식하고 처리를 시작합니다!\")\n",
    "\n",
    "    prompt = f\"\"\"\n",
    "    당신은 친절한 시니어 개발자 멘토입니다.\n",
    "    아래 개발자의 일반 개발 문의에 대해 명확하게 안내해 주세요:\n",
    "\n",
    "    {state['developer_query']}\n",
    "\n",
    "    반드시 다음 내용을 포함하여 답변하세요:\n",
    "\n",
    "    - 질문에 대해 핵심을 짚어 이해하기 쉽게 설명합니다.\n",
    "    - 공식 문서 또는 신뢰할 수 있는 학습 자료를 안내합니다.\n",
    "    - 실용적인 코드 예시나 사용 예를 함께 제공합니다.\n",
    "    - 관련하여 함께 알아두면 유용한 개념이나 도구를 추천합니다.\n",
    "\n",
    "    주니어 개발자도 이해할 수 있을 만큼 친절하고 명확하게 작성하세요.\n",
    "    \"\"\"\n",
    "\n",
    "    response = model.invoke(prompt).content\n",
    "\n",
    "    print(\"일반 개발 처리 노드 답변 생성 완료!\")\n",
    "\n",
    "    return {\n",
    "        \"response\": response,\n",
    "        \"tools_used\": [\"docs_search\", \"code_snippet_db\", \"tutorial_finder\"],\n",
    "    }\n",
    "\n",
    "\n",
    "def route_by_dev_category(state: DevSupportState):\n",
    "    print(f\"'{state['query_category']}' 노드로 라우팅합니다.\")\n",
    "    return state[\"query_category\"]\n",
    "\n",
    "\n",
    "builder = StateGraph(DevSupportState)\n",
    "\n",
    "builder.add_node(\"classify_dev_query\", classify_dev_query)\n",
    "builder.add_node(\"bug\", handle_bug)\n",
    "builder.add_node(\"architecture\", handle_architecture)\n",
    "builder.add_node(\"performance\", handle_performance)\n",
    "builder.add_node(\"devops\", handle_devops)\n",
    "builder.add_node(\"general\", handle_general_dev)\n",
    "\n",
    "builder.add_edge(START, \"classify_dev_query\")\n",
    "\n",
    "builder.add_conditional_edges(\n",
    "    \"classify_dev_query\",\n",
    "    route_by_dev_category,\n",
    "    {\n",
    "        \"bug\": \"bug\",\n",
    "        \"architecture\": \"architecture\",\n",
    "        \"performance\": \"performance\",\n",
    "        \"devops\": \"devops\",\n",
    "        \"general\": \"general\",\n",
    "    }\n",
    ")\n",
    "\n",
    "builder.add_edge(\"bug\", END)\n",
    "builder.add_edge(\"architecture\", END)\n",
    "builder.add_edge(\"performance\", END)\n",
    "builder.add_edge(\"devops\", END)\n",
    "builder.add_edge(\"general\", END)\n",
    "\n",
    "graph = builder.compile()\n",
    "bug_prompt = \"파이썬으로 FastAPI 서버를 실행하면 'NoneType object is not subscriptable' 오류가 발생하는데 원인을 모르겠어요.\"\n",
    "architecture_prompt = \"쇼핑몰 백엔드를 모놀리식에서 마이크로서비스로 전환하려고 하는데, 어떤 구조로 설계하는 게 좋을까요?\"\n",
    "performance_prompt = \"MySQL 쿼리 하나가 데이터가 10만 건을 넘어가면서 응답 속도가 갑자기 5초 이상으로 느려졌어요.\"\n",
    "devops_prompt = \"GitHub Actions로 Docker 이미지를 빌드해서 AWS ECR에 자동 배포하는 CI/CD 파이프라인을 구성하고 싶어요.\"\n",
    "general_prompt = \"React와 Next.js의 차이가 뭔지, 그리고 어떤 상황에서 Next.js를 선택해야 하는지 알고 싶어요.\"\n",
    "\n",
    "prompts = [bug_prompt, architecture_prompt, performance_prompt, devops_prompt, general_prompt]\n",
    "\n",
    "def convert_to_arg(fn):\n",
    "    return {\n",
    "    \"developer_query\": fn,\n",
    "    \"query_category\": \"\",\n",
    "    \"response\": \"\",\n",
    "    \"tools_used\": []\n",
    "}\n",
    "\n",
    "results = graph.batch([ convert_to_arg(prompt) for prompt in prompts])\n",
    "\n",
    "for result in results:\n",
    "    print('결과')\n",
    "    print(result[\"response\"])\n",
    "    print(f\"사용된 도구: {', '.join(result['tools_used'])}\")\n",
    "개발자의 질문을 분석합니다.개발자의 질문을 분석합니다.\n",
    "개발자의 질문을 분석합니다.\n",
    "\n",
    "개발자의 질문을 분석합니다.\n",
    "개발자의 질문을 분석합니다.\n",
    "분류된 카테고리 : performance\n",
    "신뢰도 : 0.98\n",
    "판단 근거 : The issue describes a sudden slowdown of a MySQL query when the number of rows exceeds 100,000, indicating a performance bottleneck such as query optimization, indexing, or resource constraints. This falls squarely under performance-related problems.\n",
    "'performance' 노드로 라우팅합니다.\n",
    "성능 관련 문제를 인식하고 처리를 시작합니다!\n",
    "분류된 카테고리 : architecture\n",
    "신뢰도 : 0.99\n",
    "판단 근거 : The question specifically asks about how to structure the backend when transitioning from monolith to microservices, which is a design/architecture concern.\n",
    "'architecture' 노드로 라우팅합니다.\n",
    "설계 관련 문제를 인식하고 처리를 시작합니다!\n",
    "분류된 카테고리 : bug\n",
    "신뢰도 : 0.99\n",
    "판단 근거 : The user reports a runtime error 'NoneType object is not subscriptable' when running a FastAPI server, which indicates a bug in code or configuration leading to an exception.\n",
    "'bug' 노드로 라우팅합니다.\n",
    "버그 관련 문제를 인식하고 처리를 시작합니다!\n",
    "분류된 카테고리 : devops\n",
    "신뢰도 : 0.98\n",
    "판단 근거 : The question focuses on automating build and deployment of Docker images using GitHub Actions to AWS ECR, which involves CI/CD, Docker, and cloud infrastructure configuration – all core topics of the devops category.\n",
    "'devops' 노드로 라우팅합니다.\n",
    "배포/인프라 관련 문제를 인식하고 처리를 시작합니다!\n",
    "분류된 카테고리 : general\n",
    "신뢰도 : 0.98\n",
    "판단 근거 : The question asks about the differences between React and Next.js and when to choose Next.js, which is about library/framework usage and general development guidance, not bug, architecture, performance, or devops.\n",
    "'general' 노드로 라우팅합니다.\n",
    "일반 개발 문의를 인식하고 처리를 시작합니다!\n",
    "버그 처리 노드 답변 생성 완료!\n",
    "아키텍처 처리 노드 답변 생성 완료!\n",
    "성능 처리 노드 답변 생성 완료!\n",
    "DevOps 처리 노드 답변 생성 완료!\n",
    "일반 개발 처리 노드 답변 생성 완료!\n",
    "결과\n",
    "## 1. 오류 메시지에서 알 수 있는 것\n",
    "\n",
    "```\n",
    "TypeError: 'NoneType' object is not subscriptable\n",
    "```\n",
    "\n",
    "- **`NoneType`** → `None` 값이 변수에 할당돼 있음\n",
    "- **`subscriptable`** → 인덱스나 키(`[]`)를 사용하려고 함\n",
    "\n",
    "따라서 코드 어느 곳에서 `None` 객체에 대해 `obj[key]` 혹은 `obj[index]` 같은 연산을 시도했을 때 발생합니다.  \n",
    "FastAPI에서 흔히 발생하는 상황은 다음과 같습니다.\n",
    "\n",
    "| 상황 | 원인 |\n",
    "|------|------|\n",
    "| **요청 파라미터를 파싱** | `request.json()` 또는 `request.body()` 가 `None` 반환 |\n",
    "| **데이터베이스 조회** | `db.query(...).first()` 가 `None` 반환 후 `.id` 같은 속성 접근 |\n",
    "| **Pydantic 모델** | `BaseModel.parse_obj()` 가 `None` 반환 후 `obj['field']` 사용 |\n",
    "| **미들웨어/데코레이터** | `request.state` 에 값이 없는데 접근 |\n",
    "| **환경 변수** | `os.getenv('KEY')` 가 `None` 이고 `value.split()` 같은 연산 수행 |\n",
    "\n",
    "## 2. 단계별 디버깅 가이드\n",
    "\n",
    "| 단계 | 체크리스트 | 실행 방법 |\n",
    "|------|------------|-----------|\n",
    "| **1. 정확한 스택 트레이스 확인** | - 오류가 발생한 파일·라인<br>- 호출 스택 | `traceback.print_exc()` 혹은 IDE 디버거 사용 |\n",
    "| **2. `None`이 되는 변수를 찾기** | - `print(type(var), var)` 혹은 `logger.debug()` | 스택 트레이스에서 해당 라인 전후에 변수 상태를 로그 |\n",
    "| **3. 입력값 검증** | - 요청 본문, 쿼리 파라미터, 헤더 | `pydantic` 모델에 `Field(..., min_length=1)` 등 |\n",
    "| **4. DB/외부 호출 결과 검증** | - `query.first()` 가 `None` 여부 | `if result is None: raise HTTPException(404)` |\n",
    "| **5. 미들웨어/데코레이터에서 `request.state` 사용** | - `request.state.xxx` 가 존재하는지 | `hasattr(request.state, 'xxx')` |\n",
    "| **6. 환경 변수 로드** | - `os.getenv()` 가 `None` | `os.environ['KEY']` 로 강제 로드하거나 `default` 지정 |\n",
    "| **7. 재현 가능한 테스트 케이스** | - `curl` 또는 `TestClient` 로 요청 | `client.post(\"/api\", json={})` 등 |\n",
    "\n",
    "## 3. 흔한 예시와 해결 코드\n",
    "\n",
    "### 예시 1: DB 조회 후 바로 인덱싱\n",
    "\n",
    "```python\n",
    "@app.get(\"/users/{user_id}\")\n",
    "async def get_user(user_id: int):\n",
    "    user = db.query(User).filter(User.id == user_id).first()\n",
    "    # ❌ user가 None일 때 user['name'] 사용\n",
    "    return {\"name\": user[\"name\"]}   # TypeError 발생\n",
    "```\n",
    "\n",
    "**수정**:\n",
    "\n",
    "```python\n",
    "@app.get(\"/users/{user_id}\")\n",
    "async def get_user(user_id: int):\n",
    "    user = db.query(User).filter(User.id == user_id).first()\n",
    "    if user is None:\n",
    "        raise HTTPException(status_code=404, detail=\"User not found\")\n",
    "    return {\"name\": user.name}   # ORM 객체는 속성 접근\n",
    "```\n",
    "\n",
    "### 예시 2: 요청 본문 파싱\n",
    "\n",
    "```python\n",
    "@app.post(\"/items\")\n",
    "async def create_item(request: Request):\n",
    "    body = await request.json()   # body가 None일 수 있음\n",
    "    name = body[\"name\"]           # TypeError\n",
    "    ...\n",
    "```\n",
    "\n",
    "**수정**:\n",
    "\n",
    "```python\n",
    "class ItemIn(BaseModel):\n",
    "    name: str\n",
    "    price: float\n",
    "\n",
    "@app.post(\"/items\")\n",
    "async def create_item(item: ItemIn):\n",
    "    # FastAPI가 자동으로 파싱해 주며 None 체크 필요 없음\n",
    "    return {\"name\": item.name, \"price\": item.price}\n",
    "```\n",
    "\n",
    "### 예시 3: 미들웨어에서 `request.state` 사용\n",
    "\n",
    "```python\n",
    "@app.middleware(\"http\")\n",
    "async def add_user_id(request: Request, call_next):\n",
    "    request.state.user_id = request.headers.get(\"X-User-Id\")\n",
    "    response = await call_next(request)\n",
    "    return response\n",
    "\n",
    "@app.get(\"/profile\")\n",
    "async def profile(request: Request):\n",
    "    user_id = request.state.user_id[\"id\"]   # user_id가 None일 수 있음\n",
    "```\n",
    "\n",
    "**수정**:\n",
    "\n",
    "```python\n",
    "@app.get(\"/profile\")\n",
    "async def profile(request: Request):\n",
    "    user_id = request.state.user_id\n",
    "    if user_id is None:\n",
    "        raise HTTPException(status_code=401, detail=\"Missing user id\")\n",
    "    return {\"user_id\": user_id}\n",
    "```\n",
    "\n",
    "### 예시 4: 환경 변수\n",
    "\n",
    "```python\n",
    "DB_URL = os.getenv(\"DATABASE_URL\")[\"host\"]   # None일 때 TypeError\n",
    "```\n",
    "\n",
    "**수정**:\n",
    "\n",
    "```python\n",
    "DB_URL = os.getenv(\"DATABASE_URL\")\n",
    "if DB_URL is None:\n",
    "    raise RuntimeError(\"DATABASE_URL 환경 변수가 설정되지 않았습니다.\")\n",
    "```\n",
    "\n",
    "## 4. 재발 방지 팁\n",
    "\n",
    "1. **명시적 None 체크**  \n",
    "   `if var is None:` 로 항상 확인하고, 필요하다면 예외를 던집니다.\n",
    "\n",
    "2. **Pydantic 모델 활용**  \n",
    "   FastAPI가 요청 바디, 쿼리 파라미터, 헤더를 자동 검증해 주므로 `Request` 객체 직접 파싱은 피합니다.\n",
    "\n",
    "3. **타입 힌트와 `Optional`**  \n",
    "   함수 시그니처에 `Optional[T]` 를 명시하면 IDE/타입 검사기가 경고를 줍니다.\n",
    "\n",
    "4. **환경 변수 로딩**  \n",
    "   `dotenv` 를 사용해 `.env` 파일을 로드하고, `os.getenv(\"KEY\")` 가 `None` 인 경우 즉시 예외를 발생시키세요.\n",
    "\n",
    "5. **테스트 커버리지**  \n",
    "   `TestClient` 로 모든 엔드포인트를 테스트하고, `None` 반환 케이스(404, 400 등)를 포함합니다.\n",
    "\n",
    "6. **로깅**  \n",
    "   `logging` 모듈을 활용해 `None`이 되는 지점을 기록하면 추후 버그 추적이 쉬워집니다.\n",
    "\n",
    "---\n",
    "\n",
    "### 정리\n",
    "\n",
    "- **오류 원인**: `None` 객체에 인덱스/키 접근 시도\n",
    "- **디버깅**: 스택 트레이스 → 변수 값 로깅 → 입력/DB/미들웨어 검증\n",
    "- **수정 예시**: `if var is None` 체크, Pydantic 모델, ORM 속성 접근\n",
    "- **예방**: 명시적 None 체크, Pydantic 활용, 환경 변수 검증, 테스트 커버리지\n",
    "\n",
    "위 가이드를 따라 한 번씩 코드를 점검해 보시면 “NoneType object is not subscriptable” 오류를 빠르게 찾아내고 재발 방지에 도움이 될 것입니다. Happy coding!\n",
    "사용된 도구: stack_trace_analyzer, code_debugger, error_log_parser\n",
    "결과\n",
    "## 1. 현 상황에 가장 적합한 아키텍처 방향\n",
    "\n",
    "| 항목 | 추천 설계 | 이유 |\n",
    "|------|-----------|------|\n",
    "| **분할 기준** | **Domain‑Driven Design (DDD) + Bounded Context** | 쇼핑몰은 “상품·카탈로그”, “주문·결제”, “재고·배송”, “회원·로그인”, “프로모션·쿠폰” 등 명확한 도메인이 존재합니다. Bounded Context를 적용하면 각 서비스가 독립적으로 발전·배포가 가능해집니다. |\n",
    "| **서비스 패턴** | **Micro‑Service + Event‑Driven (Kafka / RabbitMQ)** | 비동기 이벤트를 사용하면 서비스 간 결합도를 낮추고, 주문 처리와 재고 업데이트 같은 긴급한 흐름을 쉽게 구현할 수 있습니다. |\n",
    "| **API 설계** | **API Gateway + OpenAPI (Swagger) 기반 계약** | 외부(프론트엔드, 모바일)와 내부(서비스‑서비스) 모두에서 명확한 계약을 정의하고, 버전 관리가 용이합니다. |\n",
    "| **데이터 전략** | **Database per Service + CQRS** | 각 서비스가 자신만의 DB를 가지면서, 읽기·쓰기 모델을 분리해 성능·확장성을 높입니다. |\n",
    "| **배포 & 인프라** | **컨테이너 (Docker) + Kubernetes + Helm** | 서비스 단위로 스케일링, 롤링 배포, 서비스 디스커버리, 자동 복구가 가능합니다. |\n",
    "| **관측성** | **분산 트레이싱 (Jaeger / Zipkin), 로그 수집 (ELK), 메트릭 (Prometheus + Grafana)** | 서비스 간 호출 경로와 성능 병목을 빠르게 파악할 수 있습니다. |\n",
    "\n",
    "> **핵심**: *“DDD + Bounded Context + Event‑Driven + Database per Service + Kubernetes”* 를 기반으로 단계별로 마이크로서비스를 도입합니다.\n",
    "\n",
    "---\n",
    "\n",
    "## 2. 추천 방식의 장단점\n",
    "\n",
    "| 장점 | 단점 |\n",
    "|------|------|\n",
    "| **도메인 독립성** – 비즈니스 팀이 서비스별로 빠르게 개발·배포할 수 있음 | **운영 복잡성** – 서비스 수가 늘어나면 네트워크, 보안, 모니터링을 모두 관리해야 함 |\n",
    "| **스케일링** – 트래픽이 많은 서비스만 별도 스케일링 가능 | **데이터 일관성** – 분산 트랜잭션이 어려워 결국 이벤트 소싱/커밋 패턴을 사용해야 함 |\n",
    "| **기술 스택 다양성** – 서비스마다 가장 적합한 언어/프레임워크 선택 가능 | **배포 파이프라인** – CI/CD, 버전 관리, 롤백을 서비스별로 구성해야 함 |\n",
    "| **장애 격리** – 한 서비스 장애가 전체 시스템을 멈추지 않음 | **네트워크 레이턴시** – 서비스 호출이 많아지면 지연이 늘어날 수 있음 |\n",
    "| **관측성** – 서비스 단위로 로그·트레이스·메트릭을 수집·분석 가능 | **복잡한 테스트** – 서비스 간 상호작용을 테스트하기 위해 계약 테스트, 모킹이 필요 |\n",
    "\n",
    "---\n",
    "\n",
    "## 3. 실제 적용 시 고려해야 할 트레이드오프\n",
    "\n",
    "| 영역 | 트레이드오프 | 실무 팁 |\n",
    "|------|--------------|--------|\n",
    "| **데이터 모델** | *ACID vs Eventual Consistency* | 비즈니스 요구에 따라 `Saga` 패턴으로 보상 트랜잭션을 구현하거나, `Read Model`을 별도 DB에 두어 읽기 성능을 보장 |\n",
    "| **서비스 규모** | *작은 서비스 vs 큰 서비스* | “도메인 단위”를 기준으로 최소 2~3개의 엔티티(예: 주문, 결제, 재고)만 포함하도록 설계 → 서비스 수가 급증하지 않도록 주의 |\n",
    "| **배포 전략** | *롤링 vs 블루/그린 vs Canary* | Kubernetes의 `Deployment`와 `Service Mesh`(Istio/Linkerd)를 활용해 `Canary` 배포를 자동화 |\n",
    "| **네트워크** | *동기 vs 비동기* | 긴급 처리(주문 → 결제)에는 동기 호출을, 비즈니스 이벤트(주문 완료 → 배송 요청)에는 비동기 이벤트를 혼용 |\n",
    "| **버전 관리** | *API 버전 vs 서비스 버전* | API Gateway에서 `/v1`, `/v2` 라우팅을 분리하고, 서비스 내부에서는 `Feature Flags`로 점진적 롤아웃 |\n",
    "| **운영 비용** | *클러스터 수 vs 리소스* | `Kubernetes` 클러스터는 최소 3개의 노드로 구성하고, `Autoscaler`를 통해 트래픽 급증 시 자동 확장 |\n",
    "\n",
    "---\n",
    "\n",
    "## 4. Best Practice & 실제 사례\n",
    "\n",
    "| 사례 | 핵심 포인트 | 적용 팁 |\n",
    "|------|-------------|--------|\n",
    "| **Shopify** | “Micro‑service + API Gateway” + “Event‑driven” | Shopify는 `GraphQL` API를 사용해 프론트엔드와 백엔드를 연결. 비동기 이벤트(`Shopify Events`)를 통해 주문과 재고를 동기화. |\n",
    "| **Amazon** | “Event‑Sourcing + CQRS” | 주문 서비스는 `OrderCreated` 이벤트를 발생시키고, `OrderReadModel`은 별도 DB에 저장. |\n",
    "| **Netflix** | “Chaos Engineering + Service Mesh” | `Hystrix`와 `Istio`를 사용해 서비스 간 장애를 시뮬레이션하고, 자동 복구를 테스트. |\n",
    "| **Zalando** | “Domain‑Driven + Event‑Sourcing” | 재고와 주문은 서로 다른 서비스이며, 이벤트를 통해 상태를 동기화. |\n",
    "| **Naver Shopping** | “Strangler Fig” | 기존 모놀리식 API를 점진적으로 마이크로서비스로 교체, `API Gateway`를 통해 라우팅을 전환. |\n",
    "\n",
    "### 실무 적용 체크리스트\n",
    "\n",
    "1. **도메인 파악**  \n",
    "   - 비즈니스 팀과 협업해 Bounded Context를 정의 (예: `Catalog`, `Order`, `Payment`, `Inventory`, `User`, `Recommendation`).\n",
    "2. **서비스 설계**  \n",
    "   - 각 Context를 하나의 마이크로서비스로 구현, 최소 3~4개의 엔티티(예: Order → Order, OrderItem, Payment)만 포함.\n",
    "3. **데이터베이스**  \n",
    "   - 서비스별 독립 DB(`PostgreSQL`, `MongoDB`, `Redis`)를 사용하고, 필요 시 `Read Replica`를 별도 DB로 분리.\n",
    "4. **API & 계약**  \n",
    "   - OpenAPI 사양을 먼저 정의하고, `Contract Testing`(Pact)으로 서비스 간 계약을 검증.\n",
    "5. **이벤트 기반**  \n",
    "   - `Kafka`를 중앙 이벤트 버스에 도입, `Topic`을 도메인별로 분리 (`order-events`, `inventory-events`).\n",
    "6. **배포 파이프라인**  \n",
    "   - GitOps (ArgoCD / Flux) + Helm 차트로 배포, `Canary` 배포를 통해 위험 최소화.\n",
    "7. **관측성**  \n",
    "   - `Prometheus` + `Grafana`로 메트릭 수집, `Jaeger`로 분산 트레이싱, `ELK`로 로그 집계.\n",
    "8. **보안**  \n",
    "   - 서비스 간 인증은 `JWT` + `OAuth2` + `Istio` 사이드카 인증으로 처리.\n",
    "9. **운영 가이드**  \n",
    "   - `SRE` 문서 작성: 장애 대응 플로우, SLA 정의, `Incident Management` 프로세스.\n",
    "10. **점진적 마이그레이션**  \n",
    "    - Strangler Fig 패턴: 기존 모놀리식 엔드포인트를 새 마이크로서비스\n",
    "사용된 도구: architecture_pattern_db, tech_stack_advisor, design_doc_generator\n",
    "결과\n",
    "## 1. 가능한 성능 저하 원인(병목 지점)\n",
    "\n",
    "| # | 원인 | 징후 | 예시 |\n",
    "|---|------|------|------|\n",
    "| 1 | **인덱스 부재 / 잘못된 인덱스** | `SELECT … WHERE …` 조건이 테이블 전체를 스캔 → I/O 증가, CPU 사용량 급증 | `WHERE user_id = 12345`에 인덱스가 없으면 10만 행 중 10만 개를 읽음 |\n",
    "| 2 | **불필요한 컬럼 선택** | `SELECT *` → 네트워크 대역폭 과다, 메모리 사용 | 10만 행 × 5 KB = 500 MB 전송 |\n",
    "| 3 | **복합 조인** | 조인 조건이 비효율 → 중간 결과가 10만 행 → 재조인 | `JOIN orders ON orders.user_id = users.id` |\n",
    "| 4 | **정규화/비정규화 문제** | 중복된 데이터 저장 → 스캔 범위 확대 | 같은 `user_id`를 여러 테이블에 중복 저장 |\n",
    "| 5 | **불필요한 정렬/그룹화** | `ORDER BY`/`GROUP BY`가 인덱스를 사용하지 못하면 전체 스캔 | `ORDER BY created_at DESC` |\n",
    "| 6 | **I/O 병목** | 디스크 대기시간 증가 → 5초 이상 | SSD가 아닌 HDD, 테이블 파티셔닝 미사용 |\n",
    "| 7 | **네트워크 지연** | 클라이언트와 DB 서버가 물리적으로 멀리 있음 | 10 ms RTT × 10 만 = 1000 초 (비현실적이지만 지연 원인) |\n",
    "| 8 | **비동기 처리 부재** | 하나의 요청이 블로킹 → 전체 서비스 지연 | 같은 세션에서 5개의 쿼리를 순차 실행 |\n",
    "\n",
    "> **핵심**: 10만 건이 넘어가면서 **5 초**가 초과한 경우 가장 흔한 원인은 **인덱스 부재**와 **불필요한 정렬/그룹화**입니다.\n",
    "\n",
    "---\n",
    "\n",
    "## 2. 프로파일링 및 성능 측정 방법\n",
    "\n",
    "| 단계 | 도구 / 명령 | 목표 |\n",
    "|------|-------------|------|\n",
    "| 1 | **`EXPLAIN` / `EXPLAIN ANALYZE`** | 쿼리 실행 계획 확인 → Full Table Scan 여부 |\n",
    "| 2 | **`SHOW WARNINGS`** | 실행 계획에 경고가 있는지 확인 |\n",
    "| 3 | **`mysqldumpslow`** | 가장 오래 걸리는 쿼리 10개 추출 |\n",
    "| 4 | **`pt-query-digest`** (Percona Toolkit) | 로그를 분석 → 평균 실행 시간, I/O, CPU |\n",
    "| 5 | **`performance_schema`** | `events_statements_current`, `events_statements_history` 조회 |\n",
    "| 6 | **`mysqlslap`** | 부하 테스트 → 동시 연결 수와 응답 시간 |\n",
    "| 7 | **`sys schema`** (Percona) | `sys.schema_table_stats`, `sys.schema_index_stats` 등으로 인덱스 사용 현황 확인 |\n",
    "| 8 | **`InnoDB Buffer Pool Size`** | 메모리 캐시 비율(%) |\n",
    "| 9 | **`SHOW PROCESSLIST`** | 대기 중인 쿼리와 잠금 현황 |\n",
    "\n",
    "**측정 절차 예시**\n",
    "\n",
    "```sql\n",
    "-- 1. 실행 계획\n",
    "EXPLAIN ANALYZE SELECT * FROM orders WHERE user_id = 12345 ORDER BY created_at DESC;\n",
    "\n",
    "-- 2. 인덱스 사용 여부 확인\n",
    "SHOW INDEX FROM orders WHERE Key_name = 'idx_user_created';\n",
    "\n",
    "-- 3. 프로파일링\n",
    "SET profiling = 1;\n",
    "SELECT * FROM orders WHERE user_id = 12345 ORDER BY created_at DESC;\n",
    "SHOW PROFILE FOR QUERY 1;\n",
    "\n",
    "-- 4. sys 스키마 활용\n",
    "SELECT * FROM sys.schema_index_stats WHERE table_name='orders';\n",
    "```\n",
    "\n",
    "> **측정 지표**  \n",
    "> - **실행 시간** (ms)  \n",
    "> - **I/O**: 읽은 페이지 수, 디스크 대기시간  \n",
    "> - **CPU**: CPU 사용량, 스레드 수  \n",
    "> - **메모리**: 버퍼 풀 캐시 비율  \n",
    "\n",
    "---\n",
    "\n",
    "## 3. 우선순위가 높은 최적화 단계\n",
    "\n",
    "> **우선순위**: 1) 인덱스 → 2) 쿼리 리팩토링(불필요한 컬럼/정렬) → 3) 파티셔닝/스토리지 엔진 최적화 → 4) 캐싱 → 5) 비동기/배치 처리\n",
    "\n",
    "### 단계 1: 인덱스 최적화\n",
    "\n",
    "| 상황 | 인덱스 제안 | 예상 효과 |\n",
    "|------|-------------|-----------|\n",
    "| `WHERE user_id = ?` | `CREATE INDEX idx_user_id ON orders(user_id);` | 테이블 스캔 → 인덱스 스캔 (10만 → 10 KB) |\n",
    "| `WHERE user_id = ? ORDER BY created_at DESC` | `CREATE INDEX idx_user_created ON orders(user_id, created_at DESC);` | 정렬 비용 절감 (인덱스 자체 정렬) |\n",
    "| `WHERE status = ? AND created_at BETWEEN ? AND ?` | `CREATE INDEX idx_status_date ON orders(status, created_at);` | 조합 인덱스 사용 |\n",
    "\n",
    "> **실제 예시**  \n",
    "> - 인덱스 없을 때: `SELECT * FROM orders WHERE user_id=1` → 5 초  \n",
    "> - 인덱스 추가 후: 동일 쿼리 → 0.4 초 (12.5배 빠름)\n",
    "\n",
    "### 단계 2: 불필요한 컬럼 및 정렬 제거\n",
    "\n",
    "1. **SELECT * → 필요한 컬럼만 지정**  \n",
    "   ```sql\n",
    "   SELECT id, status, created_at FROM orders WHERE user_id = 12345;\n",
    "   ```\n",
    "   *컬럼 수 5KB → 1KB, 네트워크 4배 감소*\n",
    "\n",
    "2. **ORDER BY/ GROUP BY 최소화**  \n",
    "   - 정렬이 꼭 필요한 경우 인덱스에 포함  \n",
    "   - 아니면 `LIMIT` 없이 정렬은 피함\n",
    "\n",
    "3. **서브쿼리 → JOIN 변환**  \n",
    "   ```sql\n",
    "   SELECT o.id, o.status, u.name\n",
    "   FROM orders o\n",
    "   JOIN users u ON o.user_id = u.id\n",
    "   WHERE o.user_id = 12345;\n",
    "   ```\n",
    "\n",
    "### 단계 3: 파티셔닝 및 스토리지 엔진\n",
    "\n",
    "| 방법 | 장점 | 적용 예시 |\n",
    "|------|------|-----------|\n",
    "| **테이블 파티셔닝 (Range, Hash)** | 특정 파티션만 스캔 → I/O 감소 | `PARTITION BY RANGE (YEAR(created_at))` |\n",
    "| **InnoDB → MyISAM** | 읽기 전용 시 MyISAM이 빠를 수 있음 | **권장**: 대부분 InnoDB 사용, MyISAM은 읽기 전용 데이터에만 |\n",
    "| **압축** | 디스크 I/O 감소 | `ROW_FORMAT=COMPRESSED` |\n",
    "\n",
    "> **예시**  \n",
    "> `orders` 테이블이 10만 행이라도 월별 파티셔닝으로 `2024-04` 파티션만 스캔 → 2배 속도 향상\n",
    "\n",
    "### 단계 4: 캐싱\n",
    "\n",
    "| 캐시 종류 | 구현 방법 | 예상 효과 |\n",
    "|-----------|----------|-----------|\n",
    "| **Query Cache** (MySQL 5.7 이하) | `query_cache_type=ON` | 동일 쿼리 재실행 시 0.1 초 |\n",
    "| **Redis / Memcached** | `SELECT * FROM orders WHERE user_id=?` 결과를 캐시 | 80 %~90 % 요청 캐시율 → 0.05 초 |\n",
    "| **Application Layer Cache** | `@Cacheable` (Spring) | 재사용 가능한 비즈니스 데이터 캐시 |\n",
    "\n",
    "> **주의**: MySQL 8.0 이상에서는 Query Cache 비활성화, 대신 애플리케이션 레벨 캐시 권장.\n",
    "\n",
    "### 단계 5: 비동기 / 배치 처리\n",
    "\n",
    "1. **비동기 DB 호출**  \n",
    "   - `CompletableFuture` / `async` API 사용 → UI 블로킹 최소화\n",
    "2. **배치 업데이트**  \n",
    "   - `INSERT … ON DUPLICATE KEY UPDATE` → 10만 행을 한 번에 삽입\n",
    "3. **ETL/데이터 웨어하우스**  \n",
    "   - 실시간 조회가 필요 없으면 별도 OLAP DB에 복제\n",
    "\n",
    "---\n",
    "\n",
    "## 4. 구체적 개선 예시\n",
    "\n",
    "### 가정\n",
    "- 기존 쿼리: `SELECT * FROM orders WHERE user_id = 12345 ORDER BY created_at DESC;`\n",
    "- 데이터: 10만 행, 5 초 응답\n",
    "사용된 도구: profiler, query_analyzer, benchmark_tool, memory_inspector\n",
    "결과\n",
    "## 📌 문제를 먼저 파악하기  \n",
    "GitHub Actions → Docker → AWS ECR → 배포 파이프라인을 구축하고 싶으시다면, 가장 흔히 발생하는 이슈는 **인증/권한**·**이미지 태깅**·**ECR 접근**·**CI 워크플로우의 중복/비효율** 등입니다.  \n",
    "아래 항목을 기준으로 현재 상황을 점검해 보세요.\n",
    "\n",
    "| # | 체크리스트 | 체크 포인트 | 흔한 실수 |\n",
    "|---|------------|-------------|-----------|\n",
    "| 1 | **AWS IAM 권한** | `ecr:GetAuthorizationToken`, `ecr:PutImage`, `ecr:BatchCheckLayerAvailability`, `ecr:DescribeRepositories` 권한이 있는 역할/사용자 | `AdministratorAccess`만 사용 → 보안 위험 |\n",
    "| 2 | **GitHub Secrets** | `AWS_ACCESS_KEY_ID`, `AWS_SECRET_ACCESS_KEY`, 혹은 **OIDC** 토큰 | 비공개 리포에 저장하지 않음, 비밀번호 노출 |\n",
    "| 3 | **ECR 리포지터리 존재 여부** | `aws ecr describe-repositories` | 리포지터리 미생성 → `push` 실패 |\n",
    "| 4 | **이미지 태깅** | `latest`, `sha256`, `branch`, `date` 등 | `latest`만 사용 → 롤백 어려움 |\n",
    "| 5 | **Docker 빌드 캐시** | `--build-arg BUILDKIT_INLINE_CACHE=1` | 빌드 속도 저하 |\n",
    "| 6 | **네트워크/리전** | `aws-region` 설정 | 리전이 일치하지 않음 → 인증 토큰 만료 |\n",
    "| 7 | **CI 워크플로우 구조** | 테스트 → 빌드 → 푸시 → 배포 | 테스트 없이 바로 푸시 → 품질 저하 |\n",
    "\n",
    "> **핵심 원인**  \n",
    "> 대부분은 “**인증 토큰이 잘못된 리전**” 혹은 “**IAM 권한이 부족**”에서 비롯됩니다.  \n",
    "> 또한, **이미지 태깅이 일관되지 않으면** 운영 중에 특정 버전을 롤백하기 어렵습니다.\n",
    "\n",
    "---\n",
    "\n",
    "## 🚀 실제 운영에 바로 적용 가능한 설정 예시\n",
    "\n",
    "### 1️⃣ GitHub Secrets 설정\n",
    "\n",
    "| Secret | 값 |\n",
    "|--------|----|\n",
    "| `AWS_ROLE_TO_ASSUME` | `arn:aws:iam::123456789012:role/GitHubActionsECR` (OIDC 기반 권한 부여) |\n",
    "| `AWS_REGION` | `ap-northeast-2` |\n",
    "| `ECR_REPOSITORY` | `myapp-backend` |\n",
    "\n",
    "> **OIDC 권한 부여**  \n",
    "> GitHub Actions는 OIDC를 통해 AWS 역할을 임시 토큰으로 부여받습니다.  \n",
    "> IAM 역할에 다음 정책을 추가하세요.\n",
    "\n",
    "```json\n",
    "{\n",
    "  \"Version\": \"2012-10-17\",\n",
    "  \"Statement\": [\n",
    "    {\n",
    "      \"Effect\": \"Allow\",\n",
    "      \"Action\": [\n",
    "        \"ecr:GetAuthorizationToken\",\n",
    "        \"ecr:BatchCheckLayerAvailability\",\n",
    "        \"ecr:PutImage\",\n",
    "        \"ecr:InitiateLayerUpload\",\n",
    "        \"ecr:UploadLayerPart\",\n",
    "        \"ecr:CompleteLayerUpload\"\n",
    "      ],\n",
    "      \"Resource\": \"*\"\n",
    "    }\n",
    "  ]\n",
    "}\n",
    "```\n",
    "\n",
    "### 2️⃣ `docker-compose.yml` (옵션) – Docker Compose를 사용한다면\n",
    "\n",
    "```yaml\n",
    "version: \"3.8\"\n",
    "services:\n",
    "  backend:\n",
    "    build:\n",
    "      context: .\n",
    "      dockerfile: Dockerfile\n",
    "    image: ${ECR_REGISTRY}/${ECR_REPOSITORY}:${TAG}\n",
    "```\n",
    "\n",
    "### 3️⃣ `Dockerfile` – 빌드 캐시 활용\n",
    "\n",
    "```dockerfile\n",
    "# syntax=docker/dockerfile:1.4\n",
    "FROM node:18-alpine AS builder\n",
    "WORKDIR /app\n",
    "COPY package*.json ./\n",
    "RUN npm ci --silent\n",
    "COPY . .\n",
    "RUN npm run build\n",
    "\n",
    "FROM node:18-alpine AS runner\n",
    "WORKDIR /app\n",
    "COPY --from=builder /app/dist ./dist\n",
    "COPY package*.json ./\n",
    "RUN npm ci --only=production --silent\n",
    "EXPOSE 3000\n",
    "CMD [\"node\", \"dist/index.js\"]\n",
    "```\n",
    "\n",
    "> **빌드 캐시**  \n",
    "> `RUN npm ci` 단계는 `--no-cache` 옵션이 없으므로 Docker 빌드 캐시가 활용됩니다.\n",
    "\n",
    "### 4️⃣ GitHub Actions 워크플로우 – `ci-cd.yml`\n",
    "\n",
    "```yaml\n",
    "name: CI/CD to ECR\n",
    "\n",
    "on:\n",
    "  push:\n",
    "    branches: [ main ]\n",
    "  pull_request:\n",
    "    branches: [ main ]\n",
    "\n",
    "jobs:\n",
    "  build-and-push:\n",
    "    runs-on: ubuntu-latest\n",
    "    environment: production\n",
    "    steps:\n",
    "      - name: Checkout code\n",
    "        uses: actions/checkout@v4\n",
    "\n",
    "      - name: Set up Docker Buildx\n",
    "        uses: docker/setup-buildx-action@v3\n",
    "\n",
    "      - name: Cache Docker layers\n",
    "        uses: actions/cache@v4\n",
    "        with:\n",
    "          path: /tmp/.buildx-cache\n",
    "          key: ${{ runner.os }}-buildx-${{ hashFiles('**/Dockerfile') }}\n",
    "          restore-keys: |\n",
    "            ${{ runner.os }}-buildx-\n",
    "\n",
    "      - name: Configure AWS credentials via OIDC\n",
    "        uses: aws-actions/configure-aws-credentials@v4\n",
    "        with:\n",
    "          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}\n",
    "          aws-region: ${{ secrets.AWS_REGION }}\n",
    "\n",
    "      - name: Login to Amazon ECR\n",
    "        id: login-ecr\n",
    "        uses: aws-actions/amazon-ecr-login@v2\n",
    "\n",
    "      - name: Build and push Docker image\n",
    "        id: build-image\n",
    "        uses: docker/build-push-action@v5\n",
    "        with:\n",
    "          context: .\n",
    "          file: Dockerfile\n",
    "          push: true\n",
    "          tags: |\n",
    "            ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPOSITORY }}:${{ github.sha }}\n",
    "            ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPOSITORY }}:latest\n",
    "          build-args: |\n",
    "            NODE_ENV=production\n",
    "          cache-from: type=registry,ref=${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPOSITORY }}:latest\n",
    "          cache-to: type=inline\n",
    "\n",
    "      - name: Output image URI\n",
    "        run: echo \"Image pushed to ${{ steps.build-image.outputs.image }}\"\n",
    "```\n",
    "\n",
    "#### 주요 포인트\n",
    "\n",
    "| 단계 | 핵심 내용 |\n",
    "|------|-----------|\n",
    "| `Configure AWS credentials via OIDC` | GitHub OIDC를 활용해 **임시 토큰**을 발급받음. |\n",
    "| `Login to Amazon ECR` | `aws-actions/amazon-ecr-login@v2`는 `GetAuthorizationToken`을 자동으로 처리. |\n",
    "| `docker/build-push-action` | `push: true` → 자동 푸시. `cache-from`/`cache-to`로 빌드 속도 향상. |\n",
    "| `tags` | `sha`와 `latest` 두 태그를 동시에 푸시해 **버전 관리**와 **간편 배포**를 모두 지원. |\n",
    "\n",
    "### 5️⃣ 배포 단계 (옵션) – ECS Fargate 예시\n",
    "\n",
    "```yaml\n",
    "  deploy:\n",
    "    needs: build-and-push\n",
    "    runs-on: ubuntu-latest\n",
    "    steps:\n",
    "      - name: Configure AWS credentials via OIDC\n",
    "        uses: aws-actions/configure-aws-credentials@v4\n",
    "        with:\n",
    "          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}\n",
    "          aws-region: ${{ secrets.AWS_REGION }}\n",
    "\n",
    "      - name: Update ECS Service\n",
    "        run: |\n",
    "          aws ecs update-service \\\n",
    "            --cluster my-ecs-cluster \\\n",
    "            --service my-ecs-service \\\n",
    "            --force-new-deployment \\\n",
    "            --image ${{ steps.build-image.outputs.image }}\n",
    "```\n",
    "\n",
    "> **Blue/Green** 또는 **Canary**를 적용하려면 ECS 서비스에 두 개의 태스크 정의를 두고 `aws ecs update-service`를 두 번 호출하면 됩니다.\n",
    "\n",
    "---\n",
    "\n",
    "## 🔧 CI/CD 파이프라인 개선 단계\n",
    "\n",
    "| 단계 | 내용 | 도구/기법 |\n",
    "|------|------|-----------|\n",
    "| 1️⃣ | **분리된 테스트** | `jest`, `cypress`, `docker compose up` 테스트 |\n",
    "| 2️⃣ | **이미지 스캔** | `amazon-ecr-public` 또는 `GitHub CodeQL` + `Trivy` |\n",
    "| 3️⃣\n",
    "사용된 도구: pipeline_manager, container_registry, cloud_config_validator, log_aggregator\n",
    "결과\n",
    "## 🚀 React vs. Next.js – 차이점과 언제 Next.js를 선택할까?\n",
    "\n",
    "> **핵심**  \n",
    "> *React*는 “UI를 만들기 위한 라이브러리”이고,  \n",
    "> *Next.js*는 “React를 웹 애플리케이션으로 만들 때 필요한 모든 도구(서버 사이드 렌더링, 라우팅, 빌드, 배포)를 한 번에 제공하는 프레임워크”입니다.\n",
    "\n",
    "---\n",
    "\n",
    "### 1️⃣ React만 쓰면 되는 경우\n",
    "\n",
    "| 상황 | React만 쓰면 되는 이유 |\n",
    "|------|------------------------|\n",
    "| **SPA (Single‑Page Application)** | 페이지 간 이동이 모두 클라이언트에서 처리되므로 SSR 필요 없음 |\n",
    "| **프로토타입 / 작은 프로젝트** | 설정이 최소화되고, 번들 사이즈가 작음 |\n",
    "| **이미 서버 사이드 로직이 별도로 존재** | 백엔드 API와 프론트엔드가 완전히 분리돼 있을 때 |\n",
    "| **특정 UI 라이브러리와만 사용** | 예: React‑DND, React‑Three‑Fiber 등 |\n",
    "\n",
    "> **결론**: “단순히 UI를 렌더링하고, 모든 데이터는 API 호출로 처리한다”면 React만으로 충분합니다.\n",
    "\n",
    "---\n",
    "\n",
    "### 2️⃣ Next.js를 선택해야 할 경우\n",
    "\n",
    "| 상황 | Next.js가 주는 이점 |\n",
    "|------|--------------------|\n",
    "| **SEO가 중요한 웹사이트** | `getServerSideProps` / `getStaticProps` 로 서버 사이드 렌더링(SSR) 혹은 정적 사이트 생성(SSG) |\n",
    "| **빠른 초기 로딩** | 페이지를 미리 빌드해 두어 첫 렌더링이 빠름 |\n",
    "| **API 라우트가 필요** | 파일 기반 라우팅(`pages/api/...`) 으로 백엔드 로직을 간편하게 추가 |\n",
    "| **파일 기반 라우팅** | `pages/` 디렉터리만으로 라우트 정의 → 라우팅 코드를 직접 작성할 필요 없음 |\n",
    "| **프로그레시브 웹앱(PWA) / 오프라인 지원** | `next/pwa` 플러그인 등으로 쉽게 설정 가능 |\n",
    "| **배포가 쉽다** | Vercel(Next.js의 공식 배포 플랫폼)과 통합, GitHub Actions와도 연동 |\n",
    "| **TypeScript와 통합** | `create-next-app --ts` 로 바로 TypeScript 프로젝트 생성 |\n",
    "| **이미 존재하는 React 컴포넌트 재사용** | 기존 React 컴포넌트 그대로 가져와서 사용 가능 |\n",
    "\n",
    "> **핵심**: “서버 사이드 렌더링, 정적 사이트 생성, API 라우트, 파일 기반 라우팅 등 웹앱에 필요한 기능을 한 번에 갖고 싶다”면 Next.js가 가장 편리합니다.\n",
    "\n",
    "---\n",
    "\n",
    "## 📚 공식 문서 & 학습 자료\n",
    "\n",
    "| 자료 | 링크 |\n",
    "|------|------|\n",
    "| **React 공식 문서** | <https://reactjs.org/docs/getting-started.html> |\n",
    "| **Next.js 공식 문서** | <https://nextjs.org/docs> |\n",
    "| **Next.js 예제 리포지터리** | <https://github.com/vercel/next.js/tree/canary/examples> |\n",
    "| **Next.js 13 새로운 앱 디렉터리** | <https://nextjs.org/docs/app> |\n",
    "| **Vercel 배포 가이드** | <https://vercel.com/docs> |\n",
    "\n",
    "> **Tip**: Next.js 문서는 “Getting Started” → “Learn” → “Advanced Features” 순으로 읽으면 이해가 빨라집니다.\n",
    "\n",
    "---\n",
    "\n",
    "## 🧩 실용적인 코드 예시\n",
    "\n",
    "### 1️⃣ React SPA 예시 (Create React App)\n",
    "\n",
    "```bash\n",
    "npx create-react-app my-react-app\n",
    "cd my-react-app\n",
    "npm start\n",
    "```\n",
    "\n",
    "```tsx\n",
    "// src/App.tsx\n",
    "import React from 'react';\n",
    "import { BrowserRouter as Router, Routes, Route } from 'react-router-dom';\n",
    "import Home from './pages/Home';\n",
    "import About from './pages/About';\n",
    "\n",
    "function App() {\n",
    "  return (\n",
    "    <Router>\n",
    "      <Routes>\n",
    "        <Route path=\"/\" element={<Home />} />\n",
    "        <Route path=\"/about\" element={<About />} />\n",
    "      </Routes>\n",
    "    </Router>\n",
    "  );\n",
    "}\n",
    "\n",
    "export default App;\n",
    "```\n",
    "\n",
    "> *단순히 라우팅을 위해 `react-router`를 추가해야 함.*\n",
    "\n",
    "---\n",
    "\n",
    "### 2️⃣ Next.js 예시 (파일 기반 라우팅 + SSG)\n",
    "\n",
    "```bash\n",
    "npx create-next-app@latest my-next-app\n",
    "cd my-next-app\n",
    "npm run dev\n",
    "```\n",
    "\n",
    "```tsx\n",
    "// pages/index.tsx\n",
    "export async function getStaticProps() {\n",
    "  // 예시: 외부 API 호출\n",
    "  const res = await fetch('https://api.example.com/posts');\n",
    "  const posts = await res.json();\n",
    "\n",
    "  return { props: { posts } };\n",
    "}\n",
    "\n",
    "export default function Home({ posts }) {\n",
    "  return (\n",
    "    <div>\n",
    "      <h1>블로그 글 목록</h1>\n",
    "      <ul>\n",
    "        {posts.map((post) => (\n",
    "          <li key={post.id}>{post.title}</li>\n",
    "        ))}\n",
    "      </ul>\n",
    "    </div>\n",
    "  );\n",
    "}\n",
    "```\n",
    "\n",
    "```tsx\n",
    "// pages/api/hello.ts\n",
    "export default function handler(req, res) {\n",
    "  res.status(200).json({ message: 'Hello from API!' });\n",
    "}\n",
    "```\n",
    "\n",
    "> *`pages/api/hello.ts` 는 백엔드 API 라우트, 별도 서버 없이 바로 호출 가능.*\n",
    "\n",
    "---\n",
    "\n",
    "### 3️⃣ Next.js 13 App 디렉터리 예시 (React Server Components)\n",
    "\n",
    "```bash\n",
    "npx create-next-app@latest my-next13-app --experimental-app\n",
    "cd my-next13-app\n",
    "npm run dev\n",
    "```\n",
    "\n",
    "```tsx\n",
    "// app/page.tsx\n",
    "export default async function Home() {\n",
    "  const res = await fetch('https://api.example.com/posts');\n",
    "  const posts = await res.json();\n",
    "\n",
    "  return (\n",
    "    <div>\n",
    "      <h1>Next 13 App 디렉터리</h1>\n",
    "      <ul>\n",
    "        {posts.map((post) => (\n",
    "          <li key={post.id}>{post.title}</li>\n",
    "        ))}\n",
    "      </ul>\n",
    "    </div>\n",
    "  );\n",
    "}\n",
    "```\n",
    "\n",
    "> *React Server Components(서버에서 렌더링되는 컴포넌트)로 더 간결한 코드 작성 가능.*\n",
    "\n",
    "---\n",
    "\n",
    "## 🔧 함께 알아두면 유용한 개념 / 도구\n",
    "\n",
    "| 개념/도구 | 설명 | 링크 |\n",
    "|-----------|------|------|\n",
    "| **SSR (Server Side Rendering)** | 페이지를 서버에서 미리 렌더링해 클라이언트에 전달 | <https://nextjs.org/docs/basic-features/pages#server-side-rendering> |\n",
    "| **SSG (Static Site Generation)** | 빌드 시점에 HTML을 미리 생성 | <https://nextjs.org/docs/basic-features/pages#static-generation-recommended> |\n",
    "| **ISR (Incremental Static Regeneration)** | 정적 페이지를 일정 주기로 재생성 | <https://nextjs.org/docs/basic-features/data-fetching#incremental-static-regeneration> |\n",
    "| **React Query** | 데이터 패칭, 캐싱, 리프레시를 간편하게 | <https://react-query.tanstack.com/> |\n",
    "| **Zod** | TypeScript 기반 스키마 검증 | <https://github.com/colinhacks/zod> |\n",
    "| **Vercel** | Next.js 전용 배포 플랫폼, 자동 CDN, 프리뷰 URL 제공 | <https://vercel.com/> |\n",
    "| **TypeScript** | 정적 타입 검사, 코드 가독성 향상 | <https://www.typescriptlang.org/> |\n",
    "| **ESLint + Prettier** | 코드 품질/스타일 통일 | <https://eslint.org/>, <https://prettier.io/> |\n",
    "| **React Hook Form** | 폼 처리 + 검증 | <https://react-hook-form.com/> |\n",
    "\n",
    "> **Tip**: Next.js 프로젝트를 생성하면 `eslint`, `prettier`, `typescript`가 기본 설정돼 있으니 바로 활용할 수 있습니다.\n",
    "\n",
    "---\n",
    "\n",
    "## 📌 정리\n",
    "\n",
    "| 구분 | React | Next.js |\n",
    "|------|-------|---------|\n",
    "| **핵심** | UI 컴포넌트 라이브러리 | React 기반 풀스택 프레임워크 |\n",
    "| **라우팅** | 수동 설정 (`react-router`) | 파일 기반 라우팅 (`pages/`, `app/`) |\n",
    "| **SSR/SSG** | 직접 구현 필요 | `getServerSideProps`, `getStaticProps` |\n",
    "| **API 라우트** | 별도 백엔드 필요 | `pages/api/` |\n",
    "| **배포** | 정적 빌드 + 별도 서버 | Vercel/Netlify 등에 바로 배포 |\n",
    "| **초기 설정** | 최소 | 조금 더 복잡\n",
    "사용된 도구: docs_search, code_snippet_db, tutorial_finder"
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
